apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: {{ .Values.namespace }}  
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson | b64enc | quote }}
