pipeline {
    agent any

    environment {
        IMAGE_NAME = 'vnoah/flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        
    }

    
    stages {
        stage('Checkout') {
            steps {
                dir('docker') {
                    checkout([
                        $class: 'GitSCM',
                        branches: [[name: '*/main']], 
                        userRemoteConfigs: [[url: 'https://github.com//NoaVaturi/cicd-jenkins-project.git']]
                    ])
                }
            }
        }

        stage('Setup') {
            steps {
                dir('docker') {
                    sh "pip install -r requirements.txt"
                }  
            }
        }

        stage('Test') {
            steps {
                dir('docker') {
                    sh "pytest"
                }   
            }
        }

        stage('Login to docker hub') {
            steps {
                dir('docker') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh 'echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin'}
                }
                echo 'Login successfully'
            }
        }

        stage('Build Docker Image')
        {
            steps
            {
                dir('docker') {
                    sh 'docker build -t ${IMAGE_TAG} .'
                    echo "Docker image build successfully"
                    sh 'docker image ls'
                } 
            }
        }

        stage('Push Docker Image')
        {
            steps
            {
                dir('docker') {
                    sh 'docker push ${IMAGE_TAG}'
                    echo "Docker image push successfully"
                }
            }
        }      
    }
}